### ISSUE TITLE
Remove @types from package.json "dependencies" and place them in "devDependencies"

### ISSUE THREAD

**Issue by thernstig** [vesse/passport-ldapauth#102]
If you know how to fix the issue, make a pull request instead.

- [x ] I believe this is an issue in this library and not in the underlying libraries [ldapjs](https://github.com/joyent/node-ldapjs/) or [ldapauth-fork](https://github.com/vesse/node-ldapauth-fork). (This library is a passport strategy and does not implement the LDAP communication)

## Problem Description

Currently the list of dependencies in package.json are:

```
  "dependencies": {
    "@types/node": "*",
    "@types/passport": "^1.0.0",
    "ldapauth-fork": "^4.3.2",
    "passport-strategy": "^1.0.0"
  },
```

`@types` should always be dev-dependencies, as the declaration files are never used when the code is running. As such, the two above `@types` should be moved to dev-dependencies.

**Comment by vesse** [comment]
I don't think it's that straightforward for published modules (see eg. microsoft/types-publisher#81), but in this case it's quite likely that if a person uses this module they have passport and node in use, and if they use TypeScript they would install those dependencies by themselves so they are now moved to `devDependencies` in version `3.0.0`. But in `ldapauth-fork` I kept the `@types/ldapjs` in `dependencies` for reasons described in that linked issue.
