### ISSUE TITLE
deprecated ldapjs@2.3.3: This package has been decomissioned. 

### ISSUE THREAD

**Issue by wakabayashik** [vesse/passport-ldapauth#123]
## Problem Description
npm install shows
> npm WARN deprecated ldapjs@2.3.3: This package has been decomissioned. See https://github.com/ldapjs/node-ldapjs/blob/8ffd0bc9c149088a10ec4c1ec6a18450f76ad05d/README.md

## Steps to Reproduce

> npm install passport-ldapauth

**Comment by vesse** [comment]
Yes, not much I can do about that. Really sad to see how rude some people are.
