### ISSUE TITLE
Can't use email address as username

### ISSUE THREAD

**Issue by necramirez** [vesse/passport-ldapauth#25]
I'm using https://github.com/sdelements/lets-chat, and I ran into https://github.com/sdelements/lets-chat/issues/380, where I couldn't login using my email address when connecting via XMPP with Pidgin, although their web interface does not have that problem.

After investigating (read: inserting console.log() all around), this was my finding: https://github.com/sdelements/lets-chat/issues/380#issuecomment-87615199
_(copy-pasting it here)_
> Just confirmed it. "@" does not work.
> 
> Given the "uid@chat.company.com" format, if I pass use my email address as username, Pidgin itself breaks the "myemail@mycompany.com@chat.company.com" string into:
> * username = "myemail"
> * domain = "mycompany.com@chat.company.com"
> 
> So I tried to URL-encode my email address into "myemail%40mycompany.com", and `passport-ldapauth` simply passes it directly to the LDAP directory. It's `passport-ldapauth` that does not support email addresses as XMPP usernames.
> 
> I added this
> ```
>   username = decodeURIComponent(username);
> ```
> at https://github.com/vesse/passport-ldapauth/blob/master/lib/passport-ldapauth/strategy.js#L139 in my local install (`lets-chat/node_modules/lets-chat-ldap/node_modules/passport-ldapauth/lib/passport-ldapauth/strategy.js`) in order to test my hunch, and I can now login via Pidgin!

I've ran into a similar situation before, also concerning XMPP and trying to authenticate with LDAP, and the workaround was the same:  typing in a URL-encoded email address, substituting "@" with "%40".  I know you can look at it as a Pidgin (or other XMPP client) bug, but I'm not optimistic about them addressing it faster than you could possibly do. :-p

**Comment by vesse** [comment]
Yeah, as you noticed that's not really `passport-ldapauth` issue - it will accept whatever is given and will pass it directly to LDAP server. I won't add the `decodeURIComponent` call as such as it would of course break usernames that have characters forming valid URL encoded string. I could add an option to perform the operation though, that won't break anything.

**Comment by necramirez** [comment]
An option would be great!

**Comment by sibartlett** [comment]
Hi, Let's Chat maintainer here.

URI decoding user input shouldn't be the responsibility of passport-ldapauth, and I don't think an option needs to be added.

I think we've resolved @necramirez's use-case in the latest version of Let's Chat, but if we wanted support for URI decoding then it should be Let's Chat that does it.

**Comment by vesse** [comment]
Hi @sibartlett, that's great.
