### ISSUE TITLE
Incompatibility with node 0.12

### ISSUE THREAD

**Issue by oronbz** [vesse/passport-ldapauth#28]
Hi this module is not compatible with 0.12 since there were some breaking changes.

**Comment by vesse** [comment]
Are you referring to issue with SSL (that has been discussed eg. in #26), or issue with dtrace-provider (that has been discussed eg. in #27), both of which originate from `ldapjs`, or something else? In general this module is compatible with 0.12 as can be seen from [build status](https://travis-ci.org/vesse/passport-ldapauth)
