### ISSUE TITLE
Anonymous Queries Support

### ISSUE THREAD

**Issue by samy100** [vesse/passport-ldapauth#31]
For some reason bindCredentials can't be empty or bindDN. I wish to use your library to perform anonymous ldap queries. What's the correct way to do it? Thanks!

**Comment by vesse** [comment]
Which version are you using and how does the error show up? `bindDn` and `bindCredentials` have not been required in `ldapauth-fork`, which this library uses, for ages. Just for the record, this is an authentication strategy and not generic LDAP search utility, if you really just need to perform queries you should use [ldapjs](http://ldapjs.org/client.html) directly.

**Comment by rafaelri** [comment]
Same here for me and I am trying to authenticate against an Active Directory without providing a bind account but I couldn't get it working. I managed to get a little bit further with some changes but I was still in the dirty code approach. I'll fork and attempt a cleaner code in order to get it working.

**Comment by rafaelri** [comment]
@vesse sorry but in my case AD is configured to disallow anonymous binds. Anyways, I think we could support directly authenticating with user credentials.

**Comment by vesse** [comment]
@rafaelri does your LDAP allow binding without using the full DN? That's usually the main point of admin bind - use the username given by user to find the correct DN, and then bind using that DN together with password given by user to verify the password. Cannot say for sure, but at least most of the times I've encountered, binding can only be done with full DN.

**Comment by rafaelri** [comment]
@vesse Active Directory does. But I am not sure whether this is a good practice nor if it is widely supported. I am investigating (since I am no LDAP expert... I really only know the basics).

**Comment by rafaelri** [comment]
@vesse according to this it seems like it isn't supported: http://www.zytrax.com/books/ldap/apa/binddn.html

**Comment by rafaelri** [comment]
Do you think it is worth implementing? I guess the changes won't be that huge but I sincerely don't know whether it makes much sense and if anyone would adopt this.

**Comment by vesse** [comment]
@rafaelri No, I don't think that would be worth implementing. It may work with some LDAP servers (eg. an AD I've been using did not allow that) but I doubt there would be much use for the feature, and it would add to complexity of `node-ldapauth-fork`. 

If the server does not allow anonymous binding then you need to get credentials from the server support.
