### ISSUE TITLE
Grab user information

### ISSUE THREAD

**Issue by DaAwesomeP** [vesse/passport-ldapauth#37]
Is there a way to get a user's groups and other information too upon authentication? I need to get groups and whether or not a user is an administrator.

**Comment by vesse** [comment]
Probably yes - you can include `memberof` to `searchAttributes` to get list of group names, or if you wish to find the whole LDAP groups you can the [group options in `ldapauth-fork`](https://github.com/vesse/node-ldapauth-fork/blob/3feea43e243698bcaeffa904a7324f4d96df60e4/lib/ldapauth.js#L48-L61)
