### ISSUE TITLE
ETIMEDOUT  Error

### ISSUE THREAD

**Issue by whittssg** [vesse/passport-ldapauth#43]
Hello, I just implemented this into my node app. It all  seems to work fine for a while but then all of a sudden i get:

Error: connect ETIMEDOUT (IP of the LDAP server)

at Objects.exports._errnoException (util.js:874:11)

I also tried using just the LDAP fork that this uses and i eventually get the same error.

I have to wait a while and then it starts working again. 

I have another project where i didnt use ldapauth that authenticates against the same server and that doesnt have these issues. 

Thanks

EDIT.. I used edge for node (C# in node) in the end to do LDAP auth and it doesnt have the ETIMEDOUT issue.. So i am not sure if its an issue with this library or an issue with our LDAP server and this libary.

**Comment by vesse** [comment]
This library opens new connections on every authentication request (new `ldapauth-fork` instance) so I don't know how timeouts could be the library's fault. If you use `ldapauth-fork` directly then you would reuse the `ldapjs` clients and there is an open issue vesse/node-ldapauth-fork#23 related to connections dying.
