### ISSUE TITLE
Using passport-ldapauth with Proximo on Heroku

### ISSUE THREAD

**Issue by danieltjewett** [vesse/passport-ldapauth#49]
We have a very unique issue.  We have an app that currently uses our internal LDAP server for SSO.  We've successfully used passport-ldap for this app.  Recently, we moved the deployment of this app to Heroku for easier management.  The problem is that our internal LDAP server only allows certain IPs to make it through the firewall.  Since Heroku by default uses floating IPs, this caused a problem with our internal LDAP server because the request needs to come from one given IP.

We are in the process of evaluating Proximo as an add on with Heroku -- since it gives us a static outbound IP to meet the whitelist requirement.  With Proximo added on, we have successfully "made a connection" with the passport-ldapauth library -- and our IT departments confirms they see the request go through.  However, the response from the LDAP server never makes it back to the app.  I forked the repo and added some console.logs to see where the code was running/not running.  I currently added these consoles in `strategy.js`:

```
  ...
  console.log("before ldapauth");

  ldap = new LdapAuth(this.options.server);
  ldap.authenticate(username, password, function(err, user) {
        console.log("Coming back");
        console.log(err);
        console.log("-------------");

    ldap.close(function(){}); // We don't care about the closing
    console.log("close");
    ...
```

What the server logs is "before ldapauth", but nothing in the `authenticate` function is getting logged.  Any pointers or assistance on this would be fantastic.

**Comment by danieltjewett** [comment]
Doing a little more research, I believe it has something to do with `onConnect` not firing in this library: https://github.com/mcavage/node-ldapjs  I am posting an issue in that repo to see if I get anywhere.

**Comment by vesse** [comment]
Good that you got forward. I don't really have anything to contribute to this apart from first digging into [`ldapauth-fork`](https://github.com/vesse/node-ldapauth-fork) where the `authenticate` function is implemented, but since you got to `ldapjs` you have gone down the road already.
