### ISSUE TITLE
Finds user with wrong password

### ISSUE THREAD

**Issue by gothian** [vesse/passport-ldapauth#50]
if you have a user with password "Qwerty1"  and send a password that is lets say "Qwerty1yidgfsdkfsdk" it will still return your user as long as you have your password first in the string.

**Comment by vesse** [comment]
`passport-ldapauth` just [passes the password to `ldapauth-fork`](https://github.com/vesse/passport-ldapauth/blob/df03ccfe6542a7c9c3d9a1175fcadbd79bca5680/lib/passport-ldapauth/strategy.js#L157) which [uses the password only for LDAP bind](https://github.com/vesse/node-ldapauth-fork/blob/3ea9466ba56e1c0afedac3f40dd29470377a7514/lib/ldapauth.js#L342). If `bind` does not return an error then the user object is returned, but that is something these libraries are not in control of. I don't see how this could happen apart from you having pretty unsecure LDAP server, or a bug in `ldapjs` which I doubt.

**Comment by gothian** [comment]
I'm not that good at ldap so it might be so. but have you tried it in your environment and confirmed that it's not the case ?

**Comment by vesse** [comment]
Try eg. this [test server](http://www.forumsys.com/en/tutorials/integration-how-to/ldap/online-ldap-test-server/)

```javascript
var opts = {
  "url": "ldap://ldap.forumsys.com:389",
  "adminDn": "cn=read-only-admin,dc=example,dc=com",
  "adminPassword": "password",
  "searchBase": "dc=example,dc=com",
  "searchFilter": "(uid={{username}})"
}

var a = new LdapAuth(opts);

// Correct password for riemann is "password"
a.authenticate('riemann', 'passwordxxx', function(err, user) {
  console.log(err, user);
  a.close();
}
```

**Comment by gothian** [comment]
I have tested you test code and looks like it works well and my "bug" cannot be reproduced. 
Looks like it is my ldap server that works crapy 
thanks for the help
