### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by mepdr** [vesse/passport-ldapauth#51]
With a basic configuration I got the following error:
```events.js:160
throw er; // Unhandled 'error' event
      ^

Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1055:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:580:8)
    at TLSWrap.TLSSocket._init.ssl.onhandshakedone (_tls_wrap.js:412:38)
```
The ldap server is behind a firewall, reached through a port forwarding on the firewall.
What should I do?

**Comment by vesse** [comment]
Try [StackOverflow](http://stackoverflow.com/search?q=node.js+Error%3A+unable+to+get+local+issuer+certificate) for this kind of questions if [the documentation](https://github.com/vesse/passport-ldapauth/blob/0e7928ce4674e5662712b61fa49553ff6b223e5b/README.md#active-directory-over-ssl-example) does not help solve it. GitHub issues are more for **issues** in the library, not for general support and
