### ISSUE TITLE
Add session support

### ISSUE THREAD

**Issue by kav** [vesse/passport-ldapauth#53]
It looks like the library as it stands doesn't support sessions. If you add
```javascript
Strategy.prototype.authenticate = function(req, options) {
  var property = req._passport.instance._userProperty || 'user';
  if(req._passport.session) return this.success(req[property]);
```
to the front end of the auth function it will work. I'm not 100% this is how you will want to do it. Mind if I put together a PR for this?

**Comment by vesse** [comment]
Umm no thanks. I'm pretty sure one shouldn't use Passport internal stuff, and I haven't seen any strategy do so (see eg. [passport-local](https://github.com/jaredhanson/passport-local/blob/master/lib/strategy.js), one of the strategies implemented by the author of Passport.js).

Sessions are handled with [session middleware](http://passportjs.org/docs#sessions), eg.

```javascript
var express       = require('express'),
    session       = require('express-session'),
    cookieParser  = require('cookie-parser'),
    passport      = require('passport'),
    LdapStrategy  = require('passport-ldapauth').Strategy;

passport.serializeUser(function(user, cb) {
  cb(null, user.id);
});

passport.deserializeUser(function(id, cb) {
  yourDb.fetchDbCachedUser(id, cb);
});

passport.use(new LdapStrategy(opts, function(user, cb) {
  yourDb.storeUserToLocalDb(user, function(err, dbUser) {
    if (err) return cb(err);
    cb(null, dbUser);
  });
}));

var app = express();

app.use(express.cookieParser());
app.use(express.session({ secret: 'keyboard cat' }));
app.use(passport.initialize());
app.use(passport.session());
```

**Comment by kav** [comment]
The local strategy doesn't support sessions. There may be a cleaner way to do it. I can look at the other strategies he has developed.

**Comment by kav** [comment]
Or it could be designed to allow the ldap strategy to optionally verify the user is still valid

**Comment by visualskyrim** [comment]
Just a quick question:

Instead of storing the user fetched from the LDAP into a local db and refetching this user in deserializeUser, is it good to directly fetch the user again in the deserializeUser?
