### ISSUE TITLE
passport.authenticate never runs for Meteor login

### ISSUE THREAD

**Issue by chazsolo** [vesse/passport-ldapauth#55]
I'm writing a Meteor package that depends on passport-ldapauth and I can't seem to configure things properly to make it work. I'm attempting to log in using a test AD my team and I set up, and it works well (doing an `ldapsearch` in the terminal comes back with exactly what we want). My problem is that when I try to set up the call in Meteor, nothing happens. Here's what I have so far:

**ldap-server.js**

```
import {Accounts} from 'meteor/accounts-base';
import {Meteor} from 'meteor/meteor';

passport = Npm.require('passport');
LDAPStrategy = Npm.require('passport-ldapauth');

REQUEST_DEFAULTS = {
    server: {
        url: '',
        // ...
    }
};

function getLdapConfiguration( req, callback ) {
    console.log('getLdapConfiguration', req);

    process.nextTick(() => {
        let options = _.defaults(req, REQUEST_DEFAULTS);
        callback(null, options);
    });
}

Accounts.registerLoginHandler('ldap', request => {
    console.log('ldap request', request);
    // this request must be specified as an ldap request to pass
    if ( !request.isLdap ) {
        return undefined;
    }

    const authenticationOptions = {
        // meteor will handle sessions
        session: false,
        // ensure failures have messages
        flashFailure: true
    };

    passport.use(new LDAPStrategy(getLdapConfiguration, ( req, user, done ) => {
        return done(null, user);
    }));

    passport.initialize();

    // authenticate request
    passport.authenticate('ldapauth', authenticationOptions, ( err, user, info ) => {
        console.log('authenticate callback');
    });
});
```

The request coming in to the loginHandler has the username and password from the client, among other options. However, The console statements within the `getLdapConfiguration` function and the callback in `passport.authenticate` never fire. I'm not really sure what to do, as I've moved those functions around, included or removed `passport.initialize` in multiple places in the code, etc., but as I said, those console statements never fire. There are also no errors reported in either the client or the server.

What am I doing wrong?

**Comment by chazsolo** [comment]
Alright, I'm getting closer but still not understanding some things. I realize that `passport.authenticate` is returning a function, so I need to call it instead.

```
passport.authenticate('ldapauth', authenticationOptions')( req, res );
```

Problem is this isn't a route in Express, so I don't have a req/res object to pass into it, nor am I using SSR, so I'm unsure of how I'm supposed to call authenticate.

**Comment by vesse** [comment]
Sorry, but I've never used Meteor so I cannot really help with that, and even if I had this is not really the proper forum for general Passport.js and Meteor questions. [Stackoverflow](http://stackoverflow.com/questions/tagged/meteor) would probably work better.

**Comment by chazsolo** [comment]
Understood - thanks!
