### ISSUE TITLE
Merge vesse/node-ldapauth-fork/issues/43 for empty search bases

### ISSUE THREAD

**Issue by ansib** [vesse/passport-ldapauth#56]
[https://github.com/vesse/node-ldapauth-fork/issues/43](https://github.com/vesse/node-ldapauth-fork/issues/43)

Please merge the actual _node-ldapauth-fork_ version, if the linked ticket is closed.

**Comment by vesse** [comment]
`ldapauth-fork@2.2.5` does not require `searchBase`
