### ISSUE TITLE
Getting Binary File (Jpeg) via SearchAttributes

### ISSUE THREAD

**Issue by tokidoki11** [vesse/passport-ldapauth#57]
I notice that image returned from searchAttributes is already converted to String.

I found a research material https://github.com/mcavage/node-ldapjs/issues/137
Is there anyway that we could get the buffer instead of the converted string?

**Comment by vesse** [comment]
Yes, pass [`includeRaw: true` to ldapauth-fork](https://github.com/vesse/node-ldapauth-fork/blob/82d3e1a203615f098a159e8e1818828240ceacf1/lib/ldapauth.js#L95-L98) in `server` opts, then the returned user object should have the raw response included.

**Comment by tokidoki11** [comment]
I think you also need to give referral documentation in the readme

**Comment by vesse** [comment]
Yeah, maybe. I haven't duplicated `ldapauth-fork` documentation here, there's just a link in the README, but some of the options it accepts are more important/useful than the others, could consider adding those here as well.
