### ISSUE TITLE
Bind with user credentials

### ISSUE THREAD

**Issue by cperreault** [vesse/passport-ldapauth#59]
Hello, as @charly37 commented (https://github.com/vesse/passport-ldapauth/issues/41#issuecomment-280064136) in another issue, I was wondering how to achieve a "bind with user credentials" - instead of binding with an admin/static/stored account - with passport-ldapauth. 

Our university LDAP directory does not support anonymous bind, and it is not a good idea to let my personal account info to bind. I had experience with the LDAP Drupal module that offers an option to bind with the user credentials.

I tried the bindCredentials: '{{password}}' approach, but it does not work.

How to achieve it with current passport-ldapauth (v1.0.0)? 
Would it be possible the Asynchronous configuration retrieval? 
Or this is not currently supported? 

Thanks in advance for any help.

**Comment by cperreault** [comment]
Oh I just succeeded in doing it with Asynchronous configuration retrieval (https://github.com/vesse/passport-ldapauth#asynchronous-configuration-retrieval) by concatenating req.body.username and req.body.password like this:
bindDn: 'cn=' + req.body.username + ',OU=people,DC=example,DC=com',
bindCredentials: req.body.password
Was there a better way to achieve this?

**Comment by charly37** [comment]
Thx @cperreault  
Sounds promising. I will try your solution based on Asynch retrieval.

**Comment by maxxt** [comment]
How do you know which OU is your username from? How do you bind it in this case?
