### ISSUE TITLE
Support for searching multiple groups.

### ISSUE THREAD

**Issue by jmleep** [vesse/passport-ldapauth#60]
I've tried manipulating the search filter to allow searches for users in multiple groups.  It seems like that feature isn't supported.  Is there any way to include something like:

searchBase: ['ou=group1,o=org,c=us', ou=group2,o=org,c=us']

Or perhaps there is a way to allow an or statement in the search filter and I'm not sure how to do it?  I've tried that route and setting a higher level search base, but that also seems to fail with openLdap syntax.

searchFilter: '(uid={{username}})(|(ou=group1)(ou=group2))'

**Comment by vesse** [comment]
I _belive_ you cannot have multiple search bases, but you should be able to do that with refining your search filter. You should probably put something like this in the search filter:

```
(&(uid={{username}})(!(ou=group1)(ou=group2)))
```

There are some more examples in [ldapjs documentation](http://ldapjs.org/client.html#filter-strings) (which is what this strategy uses). The search filter syntax is standard so any examples you find should work with this library as well.
