### ISSUE TITLE
Unauthorized always

### ISSUE THREAD

**Issue by rahil471** [vesse/passport-ldapauth#65]
Hello, 
I'm not sure if this is an issue, I think there is something amiss with my implementation. Would be great if you could point me in the right direction.

I have been trying to authenticate against an open-ldap server using this library. 
I'm facing a difficulty where every request I make return unauthorized(401). 

First I was doing it against my local server, as it didn't work I tried out with one of the servers publicly available. 

Point to note is that, I'm successfully able to retrieve the user using ldapsearch cli in both cases.

Here is my app file
```
var express      = require('express'),
    passport     = require('passport'),
    bodyParser   = require('body-parser'),
    LdapStrategy = require('passport-ldapauth');
	var basicAuth = require('basic-auth');
 
var OPTS = {
  server: {
    url: 'ldap://ldap.forumsys.com',
    bindDN: 'cn=read-only-admin,dc=example,dc=com',
    bindCredentials: 'password',
    searchBase: 'ou=scientists,dc=example,dc=com',
    searchFilter: '(uid={{username}})'
  }
};
 
var app = express();
 
passport.use(new LdapStrategy(OPTS));
 
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: false}));
app.use(passport.initialize());
 
app.post('/login', passport.authenticate('ldapauth', {session: false}), function(req, res) {
  res.send({status: 'ok'});
});
 
app.listen(8080);
```

Here are the ldap server details - 
https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/

My request
```
POST
/login
body : {
	"username": "einstein",
	"password": "password"
}
```

**Comment by vesse** [comment]
I'm unable to look into this now, but maybe try with broader search base like [here](https://stackoverflow.com/a/28704872/3349511).

**Comment by rahil471** [comment]
That was precisely the solution! Thanks @vesse

**Comment by arikbidny** [comment]
@rahil471 Hey , I have a same issue , can you supply your full code ? 
what I need to put in searchFilter ? thanks

**Comment by FranckFreiburger** [comment]
look at this answer: https://stackoverflow.com/a/28704872/138579

**Comment by yang-ml** [comment]
hope this will help anyone reach this page
