### ISSUE TITLE
Feature request: Secondary server url

### ISSUE THREAD

**Issue by kareha** [vesse/passport-ldapauth#68]
Hi,

is it possible to set a secondary url as backup ldap server?
Can you add that feature?

If binding to url does not work, try the secondary url with same options (except the different url)

Thx in advance

**Comment by vesse** [comment]
Maybe try adding the same strategy with different name twice, both instances with separate config. If the first method fails, Passport calls the next. Something like:

```javascript
passport.use(new LdapStrategy('ldap1', ....));
passport.use(new LdapStrategy('ldap2', ....));
app.post('/login', passport.authenticate(['ldap1', 'ldap2']), function (req, res) { ... });
```
