### ISSUE TITLE
anonymous binding not working with the present version

### ISSUE THREAD

**Issue by MudassarHakim** [vesse/passport-ldapauth#71]
OperationsError: 000004DC: LdapErr: DSID-0C0907C2, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580

I am getting the same error even today after making the changes like

1. passed empty string for bindDN & bindCredentials 
2. didnt add bindDN & bindCredentials in the configuration

and I have also updated to the latest version passport-ldapauth 2.0.0
Kindly confirm if ldapauth supports binding anonymously or not ? If yes requesting you to elaborate the steps for the same.

I did lookup this closed [issue](https://github.com/vesse/passport-ldapauth/issues/41) but there too the solution doesn't address the inquired question and still it has been closed.

Hence I need to know if this is going to work as that will help us understand if we should go ahead with this or not.

**Comment by vesse** [comment]
Errors like `DSID-0C0907C2` come from the LDAP server and, as the comment states, the server does not allow performing the operation without a successful bind. You cannot work around this.

**Comment by zimmertr** [comment]
@vesse I am struggling with this problem for an unrelated issue and have been searching for help without much luck so far. Could you please involve the process involved in binding with a domain before joining? 

>Couldn't lookup domain short name: 000004DC: LdapErr: DSID-0C0907C2, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580
