### ISSUE TITLE
angular 6 compatible

### ISSUE THREAD

**Issue by mheidt** [vesse/passport-ldapauth#74]
I have a working angular 6 application and tried to integrate your project.

Unfortunately a ng build fails

Suddenly other packages are throwing errors like
 Can't resolve 'path' in ..\node_modules\minimatch

or
Can't resolve 'fs' in bunyan

**Comment by vesse** [comment]
Not an issue of this library. This is no different from any other Node library. If you include a Node lib to your frontend then don't, it doesn't work like that, and if not, use eg. Google to solve issues why ng build includes unrelated files.
