### ISSUE TITLE
Support for SASL GSS-API binding?

### ISSUE THREAD

**Issue by bsarkadi** [vesse/passport-ldapauth#78]
Hi there,

I'd need to use SASL with GSS-API (Kerberos 5) for binding with the LDAP server.
Can I do this using passport-ldapauth?

**Comment by vesse** [comment]
Hi,

I don’t know but suspect that it is not possible as there is an open issue about that in the project on top of which this one is implemented: https://github.com/joyent/node-ldapjs/issues/85
