### ISSUE TITLE
Problem 2001 (NO_OBJECT) erro

### ISSUE THREAD

**Issue by medaamarnadh** [vesse/passport-ldapauth#79]
## **error: 0000208D: NameErr: DSID-03100238, problem 2001 (NO_OBJECT), data 0, best match of:**

Hi LDAP team,

I am getting above error while trying to login with LDAP configuration.
The main point here is 
It is working in my local system but not working in windows 2012 server. 
Can any one help me out to resolve this problem ?
This is very important.

**Comment by vesse** [comment]
Issue template not used, and even if it was this is not an issue in the library but belongs to [StackOverflow](https://stackoverflow.com/) or some other online source.
