### ISSUE TITLE
Instalation asks for Python

### ISSUE THREAD

**Issue by jduartedj** [vesse/passport-ldapauth#82]
While trying to install it I get theis error asking for python, I don't understand.

PS W:\nodejs\timeoffq> npm install passport-ldap

> buffertools@1.1.0 install W:\nodejs\timeoffq\node_modules\buffertools
> node-gyp rebuild

W:\nodejs\timeoffq\node_modules\buffertools>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd W:\nodejs\timeoffq\node_modules\buffertools
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN timeoff@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! buffertools@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the buffertools@1.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dribeirinho\AppData\Roaming\npm-cache\_logs\2019-01-25T18_19_25_692Z-debug.log

**Comment by ChrisCheah** [comment]
I had the same issue. There are two way to resolve this:
1. Install **Python 2**. Python v3 will not work.
2. Bypass optional build using the following command.
```
npm install passport-ldapauth --no-optional
```
See https://github.com/vesse/passport-ldapauth/issues/26#issuecomment-99597964 for this option.
