### ISSUE TITLE
LDAP Search Fails Due To Spaces Inserted Into BaseDN

### ISSUE THREAD

**Issue by dimicha** [vesse/passport-ldapauth#99]
## Problem Description
When a search baseDN with multiple "dc" parts are used (ie: dc=dimi,dc=id,dc=au) spaces are inserted into the baseDN following each ','. Logging and tcpdump shows that this turns into
`dc=dimi, dc=id, dc=au`

This causes issues with some LDAP services are they do not see "dc=dimi, dc=id, dc=au" being apart of "dc=dimi,dc=id,dc=au"

Example logs:
`Jun 11 03:29:20 glauth glauth64: 03:29:20.892167 Bind ▶ DEBU 00f Bind request: bindDN: cn=serviceuser,ou=svcaccts,dc=dimi,dc=id,dc=au, BaseDN: dc=dimi,dc=id,dc=au, source: 192.168.0.131:61609`
`Jun 11 03:29:20 glauth glauth64: 03:29:20.892252 Bind ▶ DEBU 010 Bind success as cn=serviceuser,ou=svcaccts,dc=dimi,dc=id,dc=au from 192.168.0.131:61609`

`Jun 11 03:29:20 glauth glauth64: 03:29:20.893440 Search ▶ DEBU 011 Search request as cn=serviceuser,ou=svcaccts,dc=dimi,dc=id,dc=au from 192.168.0.131:61609 for (objectclass=*)`

`Jun 11 03:29:20 glauth glauth64: 2020/06/11 03:29:20 handleSearchRequest error LDAP Result Code 50 "Insufficient Access Rights": Search Error: search BaseDN dc=dimi, dc=id, dc=au is not in our BaseDN dc=dimi,dc=id,dc=au`

tcpdump showing "dc=dimi, dc=id, dc=au" is sent through: (.21 is the LDAP server, .14 is the client)
![image](https://user-images.githubusercontent.com/24503930/84342784-02b6aa80-abd9-11ea-907c-b211b3cd894e.png)

This was initially lodged https://github.com/Requarks/wiki/issues/2032 but referred here.
## Steps to Reproduce
LDAP server is [glauth](https://github.com/glauth/glauth) 
Application using passport-ldapauth is [wiki.js](https://github.com/Requarks/wiki)

If you need more information, please let me know.

**Comment by vesse** [comment]
If this is still a problem you could check with the latest release as I noticed in my tests that after updating `ldapjs` to v2 I needed to adjust a test as the spaces were not there anymore.

Closing anyways as the spaces were added by `ldapjs` or their dependency, not this passport strategy.
